

import Sidebar from "@/components/Sidebar";




export const metadata = {
  title: "Jay Parmatma - delivery center",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
 
        <div className="flex md:flex-row flex-col-reverse  ">

      <Sidebar/>
        
        {children}

        </div>
      


  );
}
