import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Jay Parmatma - delivery center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon"  href="delivery.jpg"/>
      </head>
      <body className={`${inter.className} bg-slate-100`}>
        <SessionWrapper>
        <div className=" ">

      
        
        {children}

        </div>
        </SessionWrapper>
        
        </body>
    </html>
  );
}
